### ISSUE TITLE
console directory?

### ISSUE THREAD

**Issue by clsource** [joshgoebel/wren-console#10]
In order to clearly separate wren-console from wren-cli maybe a specific directory  can be used to store wren-console specific files.

```js
├── console
│   ├── modules
│   │   ├── README.md
│   │   ├── booger.wren
│   │   └── wren_package.wren
│   ├── src
│   │   └── console.inc
│   ├── test
│   │   └── booger.wren
│   └── util
│       └── cli_to_c_string.py
```

**Comment by joshgoebel** [comment]
_I'm not convinced this is necessary or desirable._  The largest practical issue (if we work together closely) is merge conflicts but half of the Console changes apply to existing files in the CLI source tree already... so those can't (or shouldn't) be moved to a separate folder structure... and having half of Console in root and the other half in a "console" folder just makes no sense to me. The only real issue (that could get trippy) would be if CLI and Console wanted to add the same file with entirely different content - but that's a bridge I'm happy to cross when it actually happens - not prepare for in advance.

Perhaps there is some better way to organize things (in general) but I don't think it's in separating out all the console stuff from the CLI stuff like this.  I'm not (at this time) looking to build Console "on top of CLI"... the changes I do (to write it in largely Wren vs C) are simply too invasive IMHO.

**Comment by clsource** [comment]
agree
